-- MySQL Script generated by MySQL Workbench
-- Fri Sep  8 16:06:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant_company` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurant_company` ;

-- -----------------------------------------------------
-- Table `restaurant_company`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`countries` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `country_id_UNIQUE` (`country_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`cities` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_id_UNIQUE` (`city_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`quarters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`quarters` (
  `quarte_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`quarte_id`),
  UNIQUE INDEX `quarte_id_UNIQUE` (`quarte_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`addresses` (
  `addressId` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `countries_country_id` INT NOT NULL,
  `cities_city_id` INT NOT NULL,
  `quarters_quarte_id` INT NOT NULL,
  PRIMARY KEY (`addressId`, `countries_country_id`, `cities_city_id`, `quarters_quarte_id`),
  UNIQUE INDEX `addressId_UNIQUE` (`addressId` ASC) VISIBLE,
  INDEX `fk_addresses_countries1_idx` (`countries_country_id` ASC) VISIBLE,
  INDEX `fk_addresses_cities1_idx` (`cities_city_id` ASC) VISIBLE,
  INDEX `fk_addresses_quarters1_idx` (`quarters_quarte_id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_countries1`
    FOREIGN KEY (`countries_country_id`)
    REFERENCES `restaurant_company`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_addresses_cities1`
    FOREIGN KEY (`cities_city_id`)
    REFERENCES `restaurant_company`.`cities` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_addresses_quarters1`
    FOREIGN KEY (`quarters_quarte_id`)
    REFERENCES `restaurant_company`.`quarters` (`quarte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`categories` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `starter` VARCHAR(45) NOT NULL,
  `main_course` VARCHAR(45) NOT NULL,
  `dessert` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`categoryId`),
  UNIQUE INDEX `categoryId_UNIQUE` (`categoryId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`cutomers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`cutomers` (
  `customerId` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `addresses_addressId` INT NOT NULL,
  `addresses_countries_country_id` INT NOT NULL,
  `addresses_cities_city_id` INT NOT NULL,
  `addresses_quarters_quarte_id` INT NOT NULL,
  PRIMARY KEY (`customerId`, `addresses_addressId`, `addresses_countries_country_id`, `addresses_cities_city_id`, `addresses_quarters_quarte_id`),
  UNIQUE INDEX `customerId_UNIQUE` (`customerId` ASC) VISIBLE,
  INDEX `fk_cutomers_addresses1_idx` (`addresses_addressId` ASC, `addresses_countries_country_id` ASC, `addresses_cities_city_id` ASC, `addresses_quarters_quarte_id` ASC) VISIBLE,
  CONSTRAINT `fk_cutomers_addresses1`
    FOREIGN KEY (`addresses_addressId` , `addresses_countries_country_id` , `addresses_cities_city_id` , `addresses_quarters_quarte_id`)
    REFERENCES `restaurant_company`.`addresses` (`addressId` , `countries_country_id` , `cities_city_id` , `quarters_quarte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`dishes` (
  `serial_number` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `categories_categoryId` INT NOT NULL,
  PRIMARY KEY (`serial_number`, `categories_categoryId`),
  UNIQUE INDEX `serial_number_UNIQUE` (`serial_number` ASC) VISIBLE,
  INDEX `fk_dishes_categories_idx` (`categories_categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_dishes_categories`
    FOREIGN KEY (`categories_categoryId`)
    REFERENCES `restaurant_company`.`categories` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `list` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`orderId`),
  UNIQUE INDEX `orderId_UNIQUE` (`orderId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`preparations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`preparations` (
  `preparationId` INT NOT NULL AUTO_INCREMENT,
  `chef` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`preparationId`),
  UNIQUE INDEX `preparationId_UNIQUE` (`preparationId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`restaurants` (
  `restaurantId` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`restaurantId`),
  UNIQUE INDEX `restaurantId_UNIQUE` (`restaurantId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`transfers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`transfers` (
  `transferId` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`transferId`),
  UNIQUE INDEX `transferId_UNIQUE` (`transferId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`waiters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`waiters` (
  `waiterId` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `addresses_addressId` INT NOT NULL,
  `addresses_countries_country_id` INT NOT NULL,
  `addresses_cities_city_id` INT NOT NULL,
  `addresses_quarters_quarte_id` INT NOT NULL,
  `restaurants_restaurantId` INT NOT NULL,
  PRIMARY KEY (`waiterId`, `addresses_addressId`, `addresses_countries_country_id`, `addresses_cities_city_id`, `addresses_quarters_quarte_id`, `restaurants_restaurantId`),
  UNIQUE INDEX `waiterId_UNIQUE` (`waiterId` ASC) VISIBLE,
  INDEX `fk_waiters_addresses1_idx` (`addresses_addressId` ASC, `addresses_countries_country_id` ASC, `addresses_cities_city_id` ASC, `addresses_quarters_quarte_id` ASC) VISIBLE,
  INDEX `fk_waiters_restaurants1_idx` (`restaurants_restaurantId` ASC) VISIBLE,
  CONSTRAINT `fk_waiters_addresses1`
    FOREIGN KEY (`addresses_addressId` , `addresses_countries_country_id` , `addresses_cities_city_id` , `addresses_quarters_quarte_id`)
    REFERENCES `restaurant_company`.`addresses` (`addressId` , `countries_country_id` , `cities_city_id` , `quarters_quarte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_waiters_restaurants1`
    FOREIGN KEY (`restaurants_restaurantId`)
    REFERENCES `restaurant_company`.`restaurants` (`restaurantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`cutomers_has_waiters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`cutomers_has_waiters` (
  `cutomers_customerId` INT NOT NULL,
  `cutomers_addresses_addressId` INT NOT NULL,
  `cutomers_addresses_countries_country_id` INT NOT NULL,
  `cutomers_addresses_cities_city_id` INT NOT NULL,
  `cutomers_addresses_quarters_quarte_id` INT NOT NULL,
  `waiters_waiterId` INT NOT NULL,
  `waiters_addresses_addressId` INT NOT NULL,
  `waiters_addresses_countries_country_id` INT NOT NULL,
  `waiters_addresses_cities_city_id` INT NOT NULL,
  `waiters_addresses_quarters_quarte_id` INT NOT NULL,
  `orderId` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cutomers_customerId`, `cutomers_addresses_addressId`, `cutomers_addresses_countries_country_id`, `cutomers_addresses_cities_city_id`, `cutomers_addresses_quarters_quarte_id`, `waiters_waiterId`, `waiters_addresses_addressId`, `waiters_addresses_countries_country_id`, `waiters_addresses_cities_city_id`, `waiters_addresses_quarters_quarte_id`),
  INDEX `fk_cutomers_has_waiters_waiters1_idx` (`waiters_waiterId` ASC, `waiters_addresses_addressId` ASC, `waiters_addresses_countries_country_id` ASC, `waiters_addresses_cities_city_id` ASC, `waiters_addresses_quarters_quarte_id` ASC) VISIBLE,
  INDEX `fk_cutomers_has_waiters_cutomers1_idx` (`cutomers_customerId` ASC, `cutomers_addresses_addressId` ASC, `cutomers_addresses_countries_country_id` ASC, `cutomers_addresses_cities_city_id` ASC, `cutomers_addresses_quarters_quarte_id` ASC) VISIBLE,
  CONSTRAINT `fk_cutomers_has_waiters_cutomers1`
    FOREIGN KEY (`cutomers_customerId` , `cutomers_addresses_addressId` , `cutomers_addresses_countries_country_id` , `cutomers_addresses_cities_city_id` , `cutomers_addresses_quarters_quarte_id`)
    REFERENCES `restaurant_company`.`cutomers` (`customerId` , `addresses_addressId` , `addresses_countries_country_id` , `addresses_cities_city_id` , `addresses_quarters_quarte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cutomers_has_waiters_waiters1`
    FOREIGN KEY (`waiters_waiterId` , `waiters_addresses_addressId` , `waiters_addresses_countries_country_id` , `waiters_addresses_cities_city_id` , `waiters_addresses_quarters_quarte_id`)
    REFERENCES `restaurant_company`.`waiters` (`waiterId` , `addresses_addressId` , `addresses_countries_country_id` , `addresses_cities_city_id` , `addresses_quarters_quarte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`dishes_has_restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`dishes_has_restaurants` (
  `dishes_serial_number` INT UNSIGNED NOT NULL,
  `dishes_categories_categoryId` INT NOT NULL,
  `restaurants_restaurantId` INT NOT NULL,
  `preparation_id` INT NOT NULL,
  `chef` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dishes_serial_number`, `dishes_categories_categoryId`, `restaurants_restaurantId`, `preparation_id`),
  INDEX `fk_dishes_has_restaurants_restaurants1_idx` (`restaurants_restaurantId` ASC) VISIBLE,
  INDEX `fk_dishes_has_restaurants_dishes1_idx` (`dishes_serial_number` ASC, `dishes_categories_categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_dishes_has_restaurants_dishes1`
    FOREIGN KEY (`dishes_serial_number` , `dishes_categories_categoryId`)
    REFERENCES `restaurant_company`.`dishes` (`serial_number` , `categories_categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_has_restaurants_restaurants1`
    FOREIGN KEY (`restaurants_restaurantId`)
    REFERENCES `restaurant_company`.`restaurants` (`restaurantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`dishes_has_restaurants1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`dishes_has_restaurants1` (
  `dishes_serial_number` INT UNSIGNED NOT NULL,
  `dishes_categories_categoryId` INT NOT NULL,
  `restaurants_restaurantId` INT NOT NULL,
  `transfer_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dishes_serial_number`, `dishes_categories_categoryId`, `restaurants_restaurantId`, `transfer_id`),
  INDEX `fk_dishes_has_restaurants1_restaurants1_idx` (`restaurants_restaurantId` ASC) VISIBLE,
  INDEX `fk_dishes_has_restaurants1_dishes1_idx` (`dishes_serial_number` ASC, `dishes_categories_categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_dishes_has_restaurants1_dishes1`
    FOREIGN KEY (`dishes_serial_number` , `dishes_categories_categoryId`)
    REFERENCES `restaurant_company`.`dishes` (`serial_number` , `categories_categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_has_restaurants1_restaurants1`
    FOREIGN KEY (`restaurants_restaurantId`)
    REFERENCES `restaurant_company`.`restaurants` (`restaurantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`dishes_has_restaurants_has_cutomers_has_waiters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`dishes_has_restaurants_has_cutomers_has_waiters` (
  `dishes_has_restaurants_dishes_serial_number` INT UNSIGNED NOT NULL,
  `dishes_has_restaurants_dishes_categories_categoryId` INT NOT NULL,
  `dishes_has_restaurants_restaurants_restaurantId` INT NOT NULL,
  `dishes_has_restaurants_preparation_id` INT NOT NULL,
  `cutomers_has_waiters_cutomers_customerId` INT NOT NULL,
  `cutomers_has_waiters_cutomers_addresses_addressId` INT NOT NULL,
  `cutomers_has_waiters_cutomers_addresses_countries_country_id` INT NOT NULL,
  `cutomers_has_waiters_cutomers_addresses_cities_city_id` INT NOT NULL,
  `cutomers_has_waiters_cutomers_addresses_quarters_quarte_id` INT NOT NULL,
  `cutomers_has_waiters_waiters_waiterId` INT NOT NULL,
  `cutomers_has_waiters_waiters_addresses_addressId` INT NOT NULL,
  `cutomers_has_waiters_waiters_addresses_countries_country_id` INT NOT NULL,
  `cutomers_has_waiters_waiters_addresses_cities_city_id` INT NOT NULL,
  `cutomers_has_waiters_waiters_addresses_quarters_quarte_id` INT NOT NULL,
  PRIMARY KEY (`dishes_has_restaurants_dishes_serial_number`, `dishes_has_restaurants_dishes_categories_categoryId`, `dishes_has_restaurants_restaurants_restaurantId`, `dishes_has_restaurants_preparation_id`, `cutomers_has_waiters_cutomers_customerId`, `cutomers_has_waiters_cutomers_addresses_addressId`, `cutomers_has_waiters_cutomers_addresses_countries_country_id`, `cutomers_has_waiters_cutomers_addresses_cities_city_id`, `cutomers_has_waiters_cutomers_addresses_quarters_quarte_id`, `cutomers_has_waiters_waiters_waiterId`, `cutomers_has_waiters_waiters_addresses_addressId`, `cutomers_has_waiters_waiters_addresses_countries_country_id`, `cutomers_has_waiters_waiters_addresses_cities_city_id`, `cutomers_has_waiters_waiters_addresses_quarters_quarte_id`),
  INDEX `fk_dishes_has_restaurants_has_cutomers_has_waiters_cutomers_idx` (`cutomers_has_waiters_cutomers_customerId` ASC, `cutomers_has_waiters_cutomers_addresses_addressId` ASC, `cutomers_has_waiters_cutomers_addresses_countries_country_id` ASC, `cutomers_has_waiters_cutomers_addresses_cities_city_id` ASC, `cutomers_has_waiters_cutomers_addresses_quarters_quarte_id` ASC, `cutomers_has_waiters_waiters_waiterId` ASC, `cutomers_has_waiters_waiters_addresses_addressId` ASC, `cutomers_has_waiters_waiters_addresses_countries_country_id` ASC, `cutomers_has_waiters_waiters_addresses_cities_city_id` ASC, `cutomers_has_waiters_waiters_addresses_quarters_quarte_id` ASC) VISIBLE,
  INDEX `fk_dishes_has_restaurants_has_cutomers_has_waiters_dishes_h_idx` (`dishes_has_restaurants_dishes_serial_number` ASC, `dishes_has_restaurants_dishes_categories_categoryId` ASC, `dishes_has_restaurants_restaurants_restaurantId` ASC, `dishes_has_restaurants_preparation_id` ASC) VISIBLE,
  CONSTRAINT `fk_dishes_has_restaurants_has_cutomers_has_waiters_dishes_has1`
    FOREIGN KEY (`dishes_has_restaurants_dishes_serial_number` , `dishes_has_restaurants_dishes_categories_categoryId` , `dishes_has_restaurants_restaurants_restaurantId` , `dishes_has_restaurants_preparation_id`)
    REFERENCES `restaurant_company`.`dishes_has_restaurants` (`dishes_serial_number` , `dishes_categories_categoryId` , `restaurants_restaurantId` , `preparation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_has_restaurants_has_cutomers_has_waiters_cutomers_h1`
    FOREIGN KEY (`cutomers_has_waiters_cutomers_customerId` , `cutomers_has_waiters_cutomers_addresses_addressId` , `cutomers_has_waiters_cutomers_addresses_countries_country_id` , `cutomers_has_waiters_cutomers_addresses_cities_city_id` , `cutomers_has_waiters_cutomers_addresses_quarters_quarte_id` , `cutomers_has_waiters_waiters_waiterId` , `cutomers_has_waiters_waiters_addresses_addressId` , `cutomers_has_waiters_waiters_addresses_countries_country_id` , `cutomers_has_waiters_waiters_addresses_cities_city_id` , `cutomers_has_waiters_waiters_addresses_quarters_quarte_id`)
    REFERENCES `restaurant_company`.`cutomers_has_waiters` (`cutomers_customerId` , `cutomers_addresses_addressId` , `cutomers_addresses_countries_country_id` , `cutomers_addresses_cities_city_id` , `cutomers_addresses_quarters_quarte_id` , `waiters_waiterId` , `waiters_addresses_addressId` , `waiters_addresses_countries_country_id` , `waiters_addresses_cities_city_id` , `waiters_addresses_quarters_quarte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
